version: "2"
services:
  mycms:
    container_name: mycms
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/home/appCMS/mycms
      - /home/appCMS/mycms/nodetest1/
    mongo:
      container_name: mongo
      image: mongo
      volumes:
        - .data:/data/db
      ports:
        " 27017:27017"
